import type { Metadata } from "next";
import Link from "next/link";
import styles from "../for-mark.module.css";
export const metadata: Metadata={title:{absolute:"Research behind Mark H. Young’s publishing plan | RN Studio"},description:"A private, source-backed audience, market, search-intent, and competitor research dossier prepared by RN Studio.",robots:{index:false,follow:false,nocache:true},referrer:"no-referrer"};
const audiences=[
["Local and first-time buyers","Affordability is a total-cost question: payment, insurance, taxes, assessments, cash to close, appraisal, and contingencies.","Budget and preapproval → property screen → offer and valuation → inspection and disclosure → closing."],
["Move-up and high-value clients","Headline medians can hide a change in the mix of expensive sales. Sellers need a defensible pricing range, disclosure discipline, and a negotiation rationale.","Valuation → preparation → pricing → marketing → negotiation → close."],
["Condominium buyers and sellers","The unit is only part of the decision. AOAO fees, reserves, insurance, minutes, assessments, leasehold status, and financeability can change the answer.","Unit screen → building documents → financing and insurance → offer → closing review."],
["Investors and nonresident owners","Rent, vacancy, AOAO costs, insurance, tax treatment, permitted use, management, and exit friction belong in the same decision model.","Use case → constraints → underwriting → diligence → operation → exit."],
["Military and VA-eligible buyers","VA financing creates distinct occupancy, appraisal, timing, and resale questions. Mark’s direct experience with this audience still needs confirmation.","Entitlement and preapproval → property screen → offer → VA appraisal → ownership plan."],
["Referral partners","Lenders, appraisers, inspectors, title and escrow teams, insurers, attorneys, CPAs, and property managers encounter questions that useful content can answer or route responsibly.","Question → trusted introduction → coordinated decision → follow-through."]
] as const;
const clusters=[
["Oʻahu condo due diligence","AOAO fees, reserve studies, special assessments, insurance, leasehold, financeability","High-consideration buyer research","High"],
["Value and seller pricing","Home value, price versus value, comps, assessed value, pricing under uncertainty","Seller and owner problem-solving","High"],
["Oʻahu market interpretation","Market update, condo versus single-family, whether to buy or sell now","Recurring commercial investigation","High"],
["Neighborhood and property type","Kāneʻohe, Windward Oʻahu, Hawaiʻi Kai, waterfront, condo versus house","Location and fit evaluation","Medium until Mark confirms service depth"],
["Flood and insurance exposure","Flood maps, flood insurance, shoreline risk, updated 2026 designations","Address-level risk investigation","High"],
["Investor underwriting","Rental analysis, carrying costs, permitted use, downside, exit","Investor lead research","Medium until Mark confirms transaction mix"],
["VA and military decisions","VA loan, VA-approved condo, PCS horizon, buy versus rent","Niche transactional research","Exploratory until Mark confirms experience"]
] as const;
const sources=[
["Honolulu Board of REALTORS®, July 2026 Market Report","https://hicentral.com/mpr/mpr-2026-07.php"],
["Honolulu Board of REALTORS®, April 2026 Market Report","https://hicentral.com/mpr/mpr-2026-04.php"],
["UHERO, The Hawaiʻi Housing Factbook 2026","https://uhero.hawaii.edu/the-hawaii-housing-factbook-2026/"],
["Hawaiʻi DCCA, Thinking of Buying a Condominium?","https://www.cca.hawaii.gov/wp-content/uploads/2026/01/Thinking-of-Buying-a-Condominium.pdf"],
["Hawaiʻi DCCA, Real Estate Branch","https://cca.hawaii.gov/reb/"],
["Honolulu Real Property Assessment Division","https://realproperty.honolulu.gov/"],
["Honolulu DPP, Short-Term Rentals","https://www.honolulu.gov/dpp/permitting/str/"],
["Hawaiʻi Department of Taxation, HARPTA","https://tax.hawaii.gov/forms/a1_b3_6harpta/"],
["Hawaiʻi DCCA, 2026 Flood Insurance Rate Map memorandum","https://www.cca.hawaii.gov/ins/commissioners-memorandum-2026-3a-updated-flood-insurance-rate-maps/"],
["Consumer Financial Protection Bureau, Loan Estimate","https://www.consumerfinance.gov/owning-a-home/loan-estimate/"],
["Consumer Financial Protection Bureau, advisor network","https://www.consumerfinance.gov/owning-a-home/prepare/build-a-network-of-advisors/"],
["Veterans Benefits Administration, VA Home Loans","https://www.benefits.va.gov/homeloans/"],
["Hawaiʻi advertising rule, Haw. Code R. §16-99-11","https://www.law.cornell.edu/regulations/hawaii/Haw-Code-R-SS-16-99-11"],
["HUD, Fair Housing rights and obligations","https://www.hud.gov/stat/fheo/rights-obligations"]
] as const;
export default function MarkResearchPage(){return <main className={styles.page}>
<header className={styles.topbar}><Link href="/for-mark" className={styles.brand} aria-label="Return to Mark proposal"><span aria-hidden="true">RN</span><b>RN Studio</b></Link><nav aria-label="Research navigation"><Link href="/for-mark">Proposal</Link><a href="#audiences">Audiences</a><a href="#search">Search</a><a href="#sources">Sources</a></nav></header>
<section className={styles.researchHero}><p className={styles.eyebrow}>Private research dossier · 3 September 2026</p><h1>What the market gives Mark permission to own.</h1><p>This is the public-evidence layer behind the recommendation. It combines audience decision journeys, current Oʻahu market conditions, search-result language, representative competitor publishing, and professional-boundary review.</p><div className={styles.limitBox}><p><b>Direct finding:</b> Another market-update feed would disappear into an established field. The stronger opening is a recurring property-decision system: show the evidence, expose the assumptions, explain what changes the answer, and identify what must be confirmed.</p></div></section>
<section className={styles.section} id="audiences" aria-labelledby="audience-title"><p className={styles.eyebrow}>Audience and decision journeys</p><h2 id="audience-title">Six audiences, each with a different risk to resolve.</h2><div className={styles.researchGrid}>{audiences.map(([name,need,journey])=><article key={name}><h3>{name}</h3><p>{need}</p><small><b>Journey:</b> {journey}</small></article>)}</div></section>
<section className={styles.section+" "+styles.systemSection} id="search" aria-labelledby="search-title"><p className={styles.eyebrow}>Search-intent map</p><h2 id="search-title">The questions worth building around.</h2><table className={styles.researchTable}><thead><tr><th>Cluster</th><th>Representative language</th><th>Intent</th><th>Confidence</th></tr></thead><tbody>{clusters.map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table><div className={styles.limitBox}><p><b>Measurement boundary:</b> These are current search-result and public-market signals, not measured keyword volume, cost per click, or ranking difficulty. Defensible volume requires Keyword Planner or another paid dataset; conversion demand requires Mark’s Search Console, analytics, inquiry records, and interviews.</p></div></section>
<section className={styles.section} aria-labelledby="whitespace-title"><p className={styles.eyebrow}>Competitor and content whitespace</p><h2 id="whitespace-title">Do not compete where the market is already loud.</h2><div className={styles.researchGrid}><article><h3>Crowded</h3><ul><li>Monthly market summaries</li><li>Relocation and lifestyle guides</li><li>Luxury property showcases</li><li>Generic “trusted advisor” claims</li><li>Broad neighborhood overviews</li></ul></article><article><h3>Defensible opening</h3><ul><li>Annotated comparable-property analysis</li><li>Price, value, and assessed-value distinctions</li><li>Condo document and reserve-study walkthroughs</li><li>Downside and exit-risk decision memos</li><li>Seller pricing under uncertainty</li><li>“What I would verify next” checklists</li></ul></article></div><div className={styles.limitBox}><p><b>Professional boundary:</b> Mark’s public biography supports “former appraiser” or “appraisal-trained,” subject to his confirmation. The public record reviewed does not establish current appraisal licensure. Educational market analysis must not be presented as a regulated appraisal, legal advice, tax advice, lending advice, or insurance advice.</p><p><b>Advertising boundary:</b> Public assets should carry Mark’s licensed name and status, brokerage identity, required leasehold disclosure where applicable, fair-housing review, source dates, and clear referral language when another professional must answer.</p></div></section>
<section className={styles.sources} id="sources" aria-labelledby="research-sources-title"><div><p className={styles.eyebrow}>Selected authoritative sources</p><h2 id="research-sources-title">Evidence used for the recommendation.</h2><p>Competitor sites were also reviewed to identify representative publishing patterns. Their presence supports a qualitative whitespace assessment, not measured market share or search rank.</p></div><ul>{sources.map(([label,url])=><li key={url}><a className={styles.source} href={url} target="_blank" rel="noreferrer">{label}<span aria-hidden="true"> ↗</span></a></li>)}</ul></section>
<section className={styles.brief}><p className={styles.eyebrow}>What still requires Mark</p><h2>Public evidence can frame the questions. It cannot answer them for him.</h2><ol><li>Confirm his former appraisal role, terminology, and present professional boundaries.</li><li>Identify the client segments, neighborhoods, property types, and referral partners that actually matter to his business.</li><li>Review past inquiries, objections, transactions, Search Console, analytics, and directory information.</li><li>Interview clients or partners only with permission, then test language and content against real response.</li></ol><p className={styles.reply}><Link href="/for-mark">Return to the proposal</Link></p></section>
<footer className={styles.footer}><p><b>RN Studio prepared this independently.</b> Mark H. Young and True Real Estate Hawaiʻi did not commission or approve this research.</p><p>Public-source research accessed 3 September 2026. Findings are directional where first-party or paid measurement was unavailable.</p></footer></main>}
